{
    "template_name": "C:\\Users\\jshen\\Documents\\cfpdfmaker\\templates\\annotated.jinja",
    "output_dir": "C:\\Users\\jshen\\Documents\\cfpdfmaker",
    "params": {
        "heading_font_family": "Frutiger Linotype",
        "body_font_family": "EB Garamond",
        "body_font_size": "12",
        "cjk_font_family": "Noto Serif SC",
        "watermark": "C:/Users/jshen/Documents/cfpdfmaker/assets/watermarks/zeyou.png"
    },
    "filenames": [
        "C:/Users/jshen/Documents/cfpdfmaker/src/test.txt",
        "C:/Users/jshen/Documents/quickpdf/supp-assets/annotated/harvard-div-700.txt",
        "C:/Users/jshen/Documents/quickpdf/supp-assets/annotated/harvard-ec-150.txt"
    ]
}

C:/Users/jshen/Documents/quickpdf/supp-assets/annotated/harvard-div-700.txt
Traceback (most recent call last):
  File "C:\Users\jshen\Documents\cfpdfmaker\src\texutils.py", line 61, in tex2pdf
    subprocess.run(args, shell=False, check=True)
  File "c:\users\jshen\appdata\local\programs\python\python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['lualatex', '--interaction=nonstopmode', 'C:\\Users\\jshen\\Documents\\cfpdfmaker\\harvard-div-700.tex']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jshen\Documents\cfpdfmaker\src\gui.py", line 95, in convert
    texutils.tex2pdf(tex_path)
  File "C:\Users\jshen\Documents\cfpdfmaker\src\texutils.py", line 63, in tex2pdf
    raise LuaLaTeXRuntimeError(source_path) from e
texutils.LuaLaTeXRuntimeError: C:\Users\jshen\Documents\cfpdfmaker\harvard-div-700.tex


C:/Users/jshen/Documents/quickpdf/supp-assets/annotated/harvard-ec-150.txt
Traceback (most recent call last):
  File "C:\Users\jshen\Documents\cfpdfmaker\src\texutils.py", line 61, in tex2pdf
    subprocess.run(args, shell=False, check=True)
  File "c:\users\jshen\appdata\local\programs\python\python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['lualatex', '--interaction=nonstopmode', 'C:\\Users\\jshen\\Documents\\cfpdfmaker\\harvard-ec-150.tex']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jshen\Documents\cfpdfmaker\src\gui.py", line 95, in convert
    texutils.tex2pdf(tex_path)
  File "C:\Users\jshen\Documents\cfpdfmaker\src\texutils.py", line 63, in tex2pdf
    raise LuaLaTeXRuntimeError(source_path) from e
texutils.LuaLaTeXRuntimeError: C:\Users\jshen\Documents\cfpdfmaker\harvard-ec-150.tex

